import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {AppProvider} from "@/context/AppContext";

export const metadata: Metadata = {
  title: "ChatApplication-with-ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
